package foriba.com.jws1order;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "JWS1OrderPortType", targetNamespace = "http://com.foriba/JWS1Order")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.BARE, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface JWS1OrderPortType {

  /**
   * Java representation of web method [getOrderListByOrderProductName].
   */
  @javax.jws.WebMethod(operationName = "getOrderListByOrderProductName", action = "getOrderListByOrderProductName")
  @javax.jws.WebResult(name = "getOrderListByOrderProductNameResponse", targetNamespace = "http://com.foriba/JWS1Order", partName = "parameter")
  public foriba.com.jws1order.GetOrderListByOrderProductNameResponse getOrderListByOrderProductName(@javax.jws.WebParam(name = "getOrderListByOrderProductNameRequest", targetNamespace = "http://com.foriba/JWS1Order", partName = "parameter") foriba.com.jws1order.GetOrderListByOrderProductNameRequest parameter);

  /**
   * Java representation of web method [addOrder].
   */
  @javax.jws.WebMethod(operationName = "addOrder", action = "addOrder")
  @javax.jws.WebResult(name = "addOrderResponse", targetNamespace = "http://com.foriba/JWS1Order", partName = "parameter")
  public foriba.com.jws1order.AddOrderResponse addOrder(@javax.jws.WebParam(name = "addOrderRequest", targetNamespace = "http://com.foriba/JWS1Order", partName = "parameter") foriba.com.jws1order.AddOrderRequest parameter);

  /**
   * Java representation of web method [getOrderByID].
   */
  @javax.jws.WebMethod(operationName = "getOrderByID", action = "getOrderByID")
  @javax.jws.WebResult(name = "getOrderByIDResponse", targetNamespace = "http://com.foriba/JWS1Order", partName = "parameter")
  public foriba.com.jws1order.GetOrderByIDResponse getOrderByID(@javax.jws.WebParam(name = "getOrderByIDRequest", targetNamespace = "http://com.foriba/JWS1Order", partName = "parameter") foriba.com.jws1order.GetOrderByIDRequest parameter);

  /**
   * Java representation of web method [updateOrder].
   */
  @javax.jws.WebMethod(operationName = "updateOrder", action = "updateOrder")
  @javax.jws.WebResult(name = "updateOrderResponse", targetNamespace = "http://com.foriba/JWS1Order", partName = "parameter")
  public foriba.com.jws1order.UpdateOrderResponse updateOrder(@javax.jws.WebParam(name = "updateOrderRequest", targetNamespace = "http://com.foriba/JWS1Order", partName = "parameter") foriba.com.jws1order.UpdateOrderRequest parameter);

  /**
   * Java representation of web method [updateAmountByOrderedProductName].
   */
  @javax.jws.WebMethod(operationName = "updateAmountByOrderedProductName", action = "updateAmountByOrderedProductName")
  @javax.jws.WebResult(name = "updateAmountByOrderedProductNameResponse", targetNamespace = "http://com.foriba/JWS1Order", partName = "parameter")
  public foriba.com.jws1order.UpdateAmountByOrderedProductNameResponse updateAmountByOrderedProductName(@javax.jws.WebParam(name = "updateAmountByOrderedProductNameRequest", targetNamespace = "http://com.foriba/JWS1Order", partName = "parameter") foriba.com.jws1order.UpdateAmountByOrderedProductNameRequest parameter);

  /**
   * Java representation of web method [getOrderListByOrderArrivalDate].
   */
  @javax.jws.WebMethod(operationName = "getOrderListByOrderArrivalDate", action = "getOrderListByOrderArrivalDate")
  @javax.jws.WebResult(name = "getOrderListByOrderArrivalDateResponse", targetNamespace = "http://com.foriba/JWS1Order", partName = "parameter")
  public foriba.com.jws1order.GetOrderListByOrderArrivalDateResponse getOrderListByOrderArrivalDate(@javax.jws.WebParam(name = "getOrderListByOrderArrivalDateRequest", targetNamespace = "http://com.foriba/JWS1Order", partName = "parameter") foriba.com.jws1order.GetOrderListByOrderArrivalDateRequest parameter);

  /**
   * Java representation of web method [getOrderListByOrderDate].
   */
  @javax.jws.WebMethod(operationName = "getOrderListByOrderDate", action = "getOrderListByOrderDate")
  @javax.jws.WebResult(name = "getOrderListByOrderDateResponse", targetNamespace = "http://com.foriba/JWS1Order", partName = "parameter")
  public foriba.com.jws1order.GetOrderListByOrderDateResponse getOrderListByOrderDate(@javax.jws.WebParam(name = "getOrderListByOrderDateRequest", targetNamespace = "http://com.foriba/JWS1Order", partName = "parameter") foriba.com.jws1order.GetOrderListByOrderDateRequest parameter);

  /**
   * Java representation of web method [getOrderListByOrderedProductNameByAmount].
   */
  @javax.jws.WebMethod(operationName = "getOrderListByOrderedProductNameByAmount", action = "getOrderListByOrderedProductNameByAmount")
  @javax.jws.WebResult(name = "getOrderListByOrderedProductNameByAmountResponse", targetNamespace = "http://com.foriba/JWS1Order", partName = "parameter")
  public foriba.com.jws1order.GetOrderListByOrderedProductNameByAmountResponse getOrderListByOrderedProductNameByAmount(@javax.jws.WebParam(name = "getOrderListByOrderedProductNameByAmountRequest", targetNamespace = "http://com.foriba/JWS1Order", partName = "parameter") foriba.com.jws1order.GetOrderListByOrderedProductNameByAmountRequest parameter);

  /**
   * Java representation of web method [getOrderListByAmountByOrderArrivalDate].
   */
  @javax.jws.WebMethod(operationName = "getOrderListByAmountByOrderArrivalDate", action = "getOrderListByAmountByOrderArrivalDate")
  @javax.jws.WebResult(name = "getOrderListByAmountByOrderArrivalDateResponse", targetNamespace = "http://com.foriba/JWS1Order", partName = "parameter")
  public foriba.com.jws1order.GetOrderListByAmountByOrderArrivalDateResponse getOrderListByAmountByOrderArrivalDate(@javax.jws.WebParam(name = "getOrderListByAmountByOrderArrivalDateRequest", targetNamespace = "http://com.foriba/JWS1Order", partName = "parameter") foriba.com.jws1order.GetOrderListByAmountByOrderArrivalDateRequest parameter);

  /**
   * Java representation of web method [getOrderListByOrderedProductName].
   */
  @javax.jws.WebMethod(operationName = "getOrderListByOrderedProductName", action = "getOrderListByOrderedProductName")
  @javax.jws.WebResult(name = "getOrderListByOrderedProductNameResponse", targetNamespace = "http://com.foriba/JWS1Order", partName = "parameter")
  public foriba.com.jws1order.GetOrderListByOrderedProductNameResponse getOrderListByOrderedProductName(@javax.jws.WebParam(name = "getOrderListByOrderedProductNameRequest", targetNamespace = "http://com.foriba/JWS1Order", partName = "parameter") foriba.com.jws1order.GetOrderListByOrderedProductNameRequest parameter);

}
