package foriba.com.jws1order;

/**
 * Service implementation of {JWS1OrderService} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "JWS1OrderService", targetNamespace = "http://com.foriba/JWS1Order", wsdlLocation = "wsdl/foriba/com/jws1order/JWS1OrderPortTypeImplBean/JWS1OrderPortTypeImplBean.wsdl")
public class JWS1OrderService extends javax.xml.ws.Service {

  private final static java.net.URL JWS1ORDERSERVICE_WSDL_LOCATION;
  static {
    java.net.URL url = null;
    try {
		java.net.URL tmpUrl = JWS1OrderService.class.getClassLoader().getResource("wsdl/foriba/com/jws1order/JWS1OrderPortTypeImplBean/JWS1OrderPortTypeImplBean.wsdl");
		url = new java.net.URL(tmpUrl.getProtocol(), tmpUrl.getHost(), tmpUrl.getPort(), tmpUrl.getFile());
    } catch (java.net.MalformedURLException e) {
      e.printStackTrace();
    }
    JWS1ORDERSERVICE_WSDL_LOCATION = url;
  }
  /**
   * Default service constructor.
   */
  public JWS1OrderService() throws java.net.MalformedURLException {
    super(JWS1ORDERSERVICE_WSDL_LOCATION, new javax.xml.namespace.QName("http://com.foriba/JWS1Order", "JWS1OrderService"));
  }
  public JWS1OrderService(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
    super(wsdlLocation, serviceName);
  }
  /**
   * Get method for webservice port [JWS1OrderPort].
   */
  @javax.xml.ws.WebEndpoint(name = "JWS1OrderPort")
  public foriba.com.jws1order.JWS1OrderPortType getJWS1OrderPort() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://com.foriba/JWS1Order","JWS1OrderPort");
    return (foriba.com.jws1order.JWS1OrderPortType) super.getPort(portName,foriba.com.jws1order.JWS1OrderPortType.class);
  }
}
